name: HTTP Status Check

# Trigger the action on push or manually
on:
    push:
    workflow_dispatch:

jobs:
  check_http_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v2

      - name: Setup Node.js 20
        uses: actions/setup-node@v3  # Installiert die gewünschte Node-Version
        with:
          node-version: '20'         # Setze Node.js Version auf 20


      - name: Check URL Status
        run: |
          response=$(curl -o /dev/null -s -w "%{http_code}\n" https://httpstat.us/500)
          echo "HTTP Status Code: $response"
          if [ "$response" -ne 200 ]; then
            echo "Unexpected HTTP status code. Expected 200."
            exit 1
          
          fi
          echo "The website returned the expected 200 status code."